//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MolochnyKombinat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        public Customers()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int ID { get; set; }
        public string name { get; set; }
        public string inn { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public Nullable<bool> is_salesman { get; set; }
        public Nullable<bool> is_buyer { get; set; }
    
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
