//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MolochnyKombinat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        public Materials()
        {
            this.Recipes = new HashSet<Recipes>();
        }
    
        public int ID { get; set; }
        public string material_name { get; set; }
        public string code { get; set; }
        public string unit { get; set; }
        public Nullable<decimal> price { get; set; }
    
        public virtual ICollection<Recipes> Recipes { get; set; }
    }
}
