//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MolochnyKombinat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetails
    {
        public int ID { get; set; }
        public int order_id { get; set; }
        public int product_id { get; set; }
        public decimal quantity { get; set; }
        public Nullable<decimal> unit_price { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Products Products { get; set; }
    }
}
