//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MolochnyKombinat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public Orders()
        {
            this.OrderDetails = new HashSet<OrderDetails>();
        }
    
        public int ID { get; set; }
        public int customer_id { get; set; }
        public System.DateTime order_date { get; set; }
        public Nullable<decimal> total_amount { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
    }
}
