//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MolochnyKombinat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipes
    {
        public int ID { get; set; }
        public int product_id { get; set; }
        public int material_id { get; set; }
        public decimal quantity_per_unit { get; set; }
    
        public virtual Materials Materials { get; set; }
        public virtual Products Products { get; set; }
    }
}
